import http from 'http';
import archiver from 'archiver';

const generateThemeJSON = colors => {
	let themeColorsJSON = {};
	for (const key in colors) {
		themeColorsJSON = {
			...themeColorsJSON,
			[key]: hexToRGB(colors[key]),
		};
	}

	return {
		manifest_version: 2,
		name: "Chrome Theme Studio (chrometheme.studio) - Custom Theme",
		description: "This theme was generated by Chrome Theme Studio. Create your own custom Chrome Theme for free at chrometheme.studio.",
		version: "1.0",
		author: "Jamsheed Mistri (jmistri.com)",
		theme: {
			colors: themeColorsJSON
		}
	};
}

/* Credit: https://stackoverflow.com/questions/684672/how-do-i-loop-through-or-enumerate-a-javascript-object */
function hexToRGB(hex) {
	var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
	return result ? [
		parseInt(result[1], 16),
		parseInt(result[2], 16),
		parseInt(result[3], 16),
	] : null;
}


export default function handler(req, res) {
	if (req.method != 'POST' || req.body == 'undefined') {
		res.statusCode = 400;
		res.end(JSON.stringify({
			error: "invalid request",
		}));
		return;
	}

	res.writeHead(200, {
		'Content-Type': 'application/zip',
		'Content-disposition': 'attachment; filename=chrome-theme.zip'
	});

	const themeJSON = generateThemeJSON(req.body);
	const zip = archiver('zip');
	zip.pipe(res);
	zip.append(JSON.stringify(themeJSON, null, "\t"), {
		name: 'chrome-theme/manifest.json'
	}).finalize();
}
