import http from 'http'
import archiver from 'archiver'
import hexToRGB from '../../utils/HexToRGB'

const generateThemeJSON = (colors) => {
	let themeColorsJSON = {}
	for (const key in colors) {
		themeColorsJSON = {
			...themeColorsJSON,
			[key]: hexToRGB(colors[key]),
		}
	}

	return {
		manifest_version: 2,
		name: 'Chrome Theme Studio (chrometheme.studio) - Custom Theme',
		description:
			'This theme was generated by Chrome Theme Studio. Create your own custom Chrome Theme for free at chrometheme.studio.',
		version: '1.0',
		author: 'Jamsheed Mistri (jmistri.com)',
		theme: {
			colors: themeColorsJSON,
		},
	}
}

module.exports = (req, res) => {
	if (req.method != 'POST' || req.body == 'undefined') {
		return res.status(400).json({
			error: 'invalid request',
		})
	}

	res.writeHead(200, {
		'Content-Type': 'application/zip',
		'Content-disposition': 'attachment; filename=chrome-theme.zip',
	})

	const themeJSON = generateThemeJSON(req.body)
	const zip = archiver('zip')
	zip.pipe(res)
	zip
		.append(JSON.stringify(themeJSON, null, '\t'), {
			name: 'chrome-theme/manifest.json',
		})
		.finalize()
}
